# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('password2', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(choices=[('AD', 'Administrator'), ('HD', 'Helpdesk'), ('HL', 'Helpdesk Lite'), ('PW', 'Password')], default='HD', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='GWSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwHost', models.CharField(max_length=120)),
                ('gwPort', models.PositiveSmallIntegerField()),
                ('gwAdmin', models.CharField(max_length=64)),
                ('gwPass', models.CharField(max_length=64)),
            ],
        ),
    ]
