#! /bin/bash
### BEGIN INIT INFO
# Provides:          gwhelpdesk
# Required-Start:    nginx
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The main django process
# Description:       The gunicorn process that receives HTTP requests
#                    from nginx
#
### END INIT INFO
#
#
APPNAME=gwhelpdesk
USER=root
PATH=/bin:/usr/bin:/sbin:/usr/sbin
APPMODULE=gwhelp.wsgi:application
DAEMON=gunicorn
BIND=127.0.0.1:8000
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/$DAEMON.log
WORKERS=3

. /lib/lsb/init-functions
. /etc/rc.status

rc_reset

case "$1" in
  start)
        cd /var/gwhelpdesk
        echo "Starting " "$APPNAME"
        #source $ACTIVATE
        $DAEMON --daemon --bind=$BIND --pid=$PIDFILE --workers=$WORKERS --user=$USER --log-file=$LOGFILE $APPMODULE
        rc_status -v
    ;;
  stop)
        echo "Stopping " "$APPNAME"
        killproc -p $PIDFILE $DAEMON
        rc_status -v
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    rc_status -v
    ;;
  status)
    if [[ -e $PIDFILE ]]
    then
        read < ${PIDFILE} PID

    else
        rc_failed 3
    fi

    echo -n "Checking $APPNAME worker status"
    /sbin/checkproc -p $PIDFILE $DAEMON
    rc_status -v
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;

esac

rc_exit